import type { RouteCandidate } from "@/features/agent/schemas/route-candidate.schema";
import type { RouteProvider } from "@/features/routes/providers/route-provider.types";

type OrsFeature = {
  geometry?: { coordinates?: Array<[number, number]> };
  properties?: {
    summary?: { distance?: number; duration?: number; ascent?: number; descent?: number };
    extras?: unknown;
  };
};

type OrsResponse = {
  features?: OrsFeature[];
};

export const openRouteServiceProvider: RouteProvider = {
  id: "openrouteservice",
  name: "OpenRouteService",
  async isAvailable(input, context) {
    return Boolean(
      context.enableExternalRouteSearch &&
        context.orsApiKey &&
        input.planInput.startLocation.lat != null &&
        input.planInput.startLocation.lng != null &&
        ["external_route", "not_sure", "flat", "low_traffic", "riverside", "route_exploration"].includes(input.planInput.routePreference)
    );
  },
  async findCandidates(input, context) {
    if (!(await this.isAvailable(input, context))) return [];
    const start = input.planInput.startLocation;
    if (start.lat == null || start.lng == null || !context.orsApiKey) return [];

    const targetKm = estimateTargetDistance(input.planInput.durationMinutes, input.planInput.goal);
    const coordinates = buildSimpleLoopCoordinates(start.lng, start.lat, targetKm);
    const response = await fetch("https://api.openrouteservice.org/v2/directions/cycling-regular/geojson", {
      method: "POST",
      headers: {
        authorization: context.orsApiKey,
        "content-type": "application/json",
        accept: "application/json"
      },
      body: JSON.stringify({
        coordinates,
        elevation: true,
        extra_info: ["surface", "steepness"],
        instructions: false
      })
    });

    if (!response.ok) return [];
    const json = (await response.json()) as OrsResponse;
    const feature = json.features?.[0];
    if (!feature) return [];

    const summary = feature.properties?.summary;
    const polyline = feature.geometry?.coordinates?.length ? encodeCoordinateJson(feature.geometry.coordinates) : null;
    const distanceKm = summary?.distance ? summary.distance / 1000 : targetKm;
    const durationMinutes = summary?.duration ? Math.round(summary.duration / 60) : input.planInput.durationMinutes;

    const candidate: RouteCandidate = {
      id: `ors-${Math.round(start.lat * 1000)}-${Math.round(start.lng * 1000)}-${input.planInput.durationMinutes}`,
      name: `${start.label ?? "Selected start"} cycling loop`,
      source: "external_api",
      provider: "openrouteservice",
      region: start.label,
      routeType: input.planInput.goal === "climbing" ? "rolling" : "endurance",
      distanceKm: Math.round(distanceKm * 10) / 10,
      elevationM: summary?.ascent ?? null,
      durationMinutes,
      difficulty: classifyDifficulty(distanceKm, summary?.ascent ?? 0),
      suitableGoals: [input.planInput.goal, "endurance", "route_exploration"],
      polyline,
      mapPreviewAvailable: Boolean(polyline),
      routeUrl: null,
      basedOnActivityId: null,
      safetyNotes: ["External route geometry is generated from open map data; verify road suitability before riding."],
      notes: "Generated by OpenRouteService from the selected start location.",
      score: 0,
      scoreReasons: ["generated from the selected start location with an official routing API"]
    };
    return [candidate];
  }
};

function estimateTargetDistance(durationMinutes: number, goal: string) {
  const speedKmh = goal === "recovery" ? 18 : goal === "climbing" ? 16 : 23;
  return Math.max(8, Math.round((durationMinutes / 60) * speedKmh));
}

function buildSimpleLoopCoordinates(lng: number, lat: number, targetKm: number): Array<[number, number]> {
  const offset = Math.min(0.18, Math.max(0.025, targetKm / 900));
  return [
    [lng, lat],
    [lng + offset, lat + offset / 2],
    [lng + offset / 2, lat + offset],
    [lng, lat]
  ];
}

function classifyDifficulty(distanceKm: number, elevationM: number): RouteCandidate["difficulty"] {
  if (elevationM >= 900 || distanceKm >= 100) return "hard";
  if (elevationM >= 350 || distanceKm >= 60) return "moderate";
  return "easy";
}

function encodeCoordinateJson(coordinates: Array<[number, number]>) {
  return JSON.stringify(coordinates.map(([lng, lat]) => [lat, lng]));
}
